sudo: required

services: 
  - docker

before_install:
  - docker build -t jaseel44/react-test -f ./client/Dockerfile.dev ./client  

script:
  - docker run -e CI=true jaseel44/react-test npm run test --coverage

after_success:
  - docker build -t jaseel44/multi-client ./client
  - docker build -t jaseel44/multi-nginx ./nginx  
  - docker build -t jaseel44/multi-server ./server  
  - docker build -t jaseel44/multi-worker ./worker  

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jaseel44/multi-client
  - docker push jaseel44/multi-nginx  
  - docker push jaseel44/multi-server
  - docker push jaseel44/multi-worker 

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"vdv
  app: "multidocker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-445198795790"
  bucket_path: "docker-react"
  on :
    branch: master
    access_key_id: $AWS_ACCES_KEY
    secret_acces_key: $AWS_SECRET_KEY  
